name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the action on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Specify the version of Node.js

      - name: Install pnpm
        run: npm install -g pnpm  # Install pnpm globally

      - name: Install dependencies
        run: pnpm install  # Install the dependencies using pnpm

      - name: Build the project
        run: pnpm run build  # Build the project

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # The folder where your build outputs
